name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
   
    - name: Update repositories
      run: sudo apt-get update
   
    - name: Install libraries
      run: sudo apt-get install -y build-essential git cmake libgl-dev libgl1 libglm-dev libglfw3-dev libglfw3 libglew-dev libglew2.2  libcmocka-dev libcmocka0 libstb-dev

    - name: Run tests
      run: mkdir build && cd build && cmake .. && make check
