name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
   
    - name: Update repositories
      run: apt-get update
   
    - name: Install libraries
      run: apt-get install -y build-essential libcmocka-dev libgl-dev libglew-dev libglfw3-dev

    - name: Run tests
      run: make -s clean test

#    - name: configure
#      run: ./configure

#    - name: Install dependencies
#      run: make

#    - name: Run check
#      run: make check

#    - name: Run distcheck
#      run: make distcheck
