name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
   
    - name: Update repositories
      run: sudo apt-get update
   
    - name: Install libraries
      run: sudo apt-get install -y build-essential git cmake libcmocka0 libcmocka-dev libgl-dev libglew-dev libglfw3-dev libglm-dev libstb-dev

    - name: Run tests
      run: mkdir build && cd build && cmake .. && make check
